//Uncomment lines to remove them from Eden Editor

//Editor Preferences
//Make sure to reset the preferences to the default values first
#define HIDE_ENH_INTERFACE
#define HIDE_ENH_DEBUGOPTIONS

//Environment Attributes
#define HIDE_ENH_VISUALSETTINGS
#define HIDE_ENH_TIMEMULTIPLIER

//General Attributes
#define HIDE_ENH_AIRDROP
#define HIDE_ENH_AMBIENTFLYBY
#define HIDE_ENH_ESTABLISHINGSHOT
#define HIDE_ENH_INTROTEXT
#define HIDE_ENH_MAPINDICATORS
#define HIDE_ENH_MISSIONENDING
#define HIDE_ENH_SPR
#define HIDE_ENH_VOLUME
#define HIDE_ENH_ADDOBJECTSTOZEUS

//Multiplayer Attributes
#define HIDE_ENH_DYNAMICSKILL
#define HIDE_ENH_TICKETSBLUFOR
#define HIDE_ENH_TICKETSOPFOR
#define HIDE_ENH_TICKETSINDFOR
#define HIDE_ENH_TICKETSCIVFOR
#define HIDE_ENH_SAVELOADOUT
#define HIDE_ENH_DYNAMICGROUPS

//Group Attributes
#define HIDE_ENH_GROUPMARKER
#define HIDE_ENH_TASKPATROL

//Trigger Attribute
#define HIDE_ENH_HIDETERRAINOBJECTS

//Object Attributes
#define HIDE_ENH_ALLOWCREWINIMMOBILE
#define HIDE_ENH_ALLOWSPRINT
#define HIDE_ENH_DEBUGPATH
#define HIDE_ENH_DISABLENVGE
#define HIDE_ENH_DISABLETIE
#define HIDE_ENH_DOSTOP
#define HIDE_ENH_ENABLEHEADLIGHTS
#define HIDE_ENH_ENGINEON
#define HIDE_ENH_FORCEWALK
#define HIDE_ENH_LIMITSPEED
#define HIDE_ENH_MAKEHOSTAGE
#define HIDE_ENH_PARACHUTE
#define HIDE_ENH_MAKEHOSTAGE
#define HIDE_ENH_PARACHUTE
#define HIDE_ENH_REMOVEFROMREMAINSCOLLECTOR
#define HIDE_ENH_SETCAPTIVE
#define HIDE_ENH_SPR
#define HIDE_ENH_ALLOWFLEEING
#define HIDE_ENH_AMBIENTANIMATIONS
#define HIDE_ENH_FEATURETYPE
#define HIDE_ENH_FORCEFLAG
#define HIDE_ENH_SETMASS
#define HIDE_ENH_ADDGUNLIGHT
#define HIDE_ENH_VIRTUALARSENAL
#define HIDE_ENH_ADVANCEDDAMAGEVEHICLE
#define HIDE_ENH_ADVANCEDSKILL
#define HIDE_ENH_DISABLEAI
#define HIDE_ENH_ADVANCEDDAMAGEUNIT
#define HIDE_ENH_HOLDACTION
#define HIDE_ENH_UNITTRAITS