//Uncomment lines to remove them from Eden Editor

//Editor Preferences
//Make sure to reset the preferences to the default values first
//#define HIDE_ENH_DEBUGOPTIONS
//#define HIDE_ENH_DYNAMICVIEWDISTANCE
//#define HIDE_ENH_INTERFACE

//Environment Attributes
//#define HIDE_ENH_TIMEMULTIPLIER
//#define HIDE_ENH_VISUALSETTINGS

//General Attributes
//#define HIDE_ENH_ADDOBJECTSTOZEUS
//#define HIDE_ENH_AIRDROP
//#define HIDE_ENH_AMBIENTFLYBY
//#define HIDE_ENH_BRIEFING
//#define HIDE_ENH_ESTABLISHINGSHOT
//#define HIDE_ENH_INTROTEXT
//#define HIDE_ENH_MAPINDICATORS
//#define HIDE_ENH_MISSIONENDING
//#define HIDE_ENH_SPR
//#define HIDE_ENH_VOLUME

//Multiplayer Attributes
//#define HIDE_ENH_DYNAMICGROUPS
//#define HIDE_ENH_RESPAWNTICKETS
//#define HIDE_ENH_SAVELOADOUT

//Group Attributes
//#define HIDE_ENH_GROUPMARKER
//#define HIDE_ENH_TASKPATROL

//Object Attributes
//#define HIDE_ENH_ADDGUNLIGHT
//#define HIDE_ENH_ADVANCEDDAMAGEUNIT
//#define HIDE_ENH_ADVANCEDDAMAGEVEHICLE
//#define HIDE_ENH_AI
//#define HIDE_ENH_ALLOWCREWINIMMOBILE
//#define HIDE_ENH_ALLOWSPRINT
//#define HIDE_ENH_AMBIENTANIMATIONS
//#define HIDE_ENH_DISABLENVGE
//#define HIDE_ENH_DISABLETIE
//#define HIDE_ENH_DOSTOP
//#define HIDE_ENH_ENABLEHEADLIGHTS
//#define HIDE_ENH_ENGINEON
//#define HIDE_ENH_FEATURETYPE
//#define HIDE_ENH_FORCEFLAG
//#define HIDE_ENH_FORCEWALK
//#define HIDE_ENH_HOLDACTION
//#define HIDE_ENH_LIMITSPEED
//#define HIDE_ENH_MAKEHOSTAGE
//#define HIDE_ENH_PARACHUTE
//#define HIDE_ENH_REMOVEFROMREMAINSCOLLECTOR
//#define HIDE_ENH_SETCAPTIVE
//#define HIDE_ENH_SETMASS
//#define HIDE_ENH_UNITTRAITS
//#define HIDE_ENH_VIRTUALARSENAL