//Uncomment lines to remove them from Eden Editor

private _menuStripBlacklist =
[
  //Main Folders
  //"STR_ENH_FOLDER_ABOUT",
  //Help
  //"STR_ENH_FOLDER_WIKI",
  //"STR_ENH_HELP_GETEXTENSIONS",
  //Utilities
  //"STR_ENH_FOLDER_UTILITIES",
  //"STR_ENH_TOOLS_3DENCAM",
  //"STR_ENH_TOOLS_3DENRADIO",
  //"STR_ENH_TOOLS_ACTIONCREATOR",
  //"STR_ENH_TOOLS_BATCHNAMING",
  //"STR_ENH_TOOLS_BATCHREPLACE",
  //"STR_ENH_TOOLS_BRIEFINGEDITOR",
  //"STR_ENH_TOOLS_CFGDISABLEDCOMMANDS",
  //"STR_ENH_TOOLS_CFGSENTENCESBROWSER",
  //"STR_ENH_TOOLS_JUKEBOX",
  //"STR_ENH_TOOLS_MOONPHASES",
  //"STR_ENH_TOOLS_PRINTCONFIG",
  //"STR_ENH_TOOLS_SCENARIOATTRIBUTESMANAGER",
  //"STR_ENH_TOOLS_SCRIPTCOMMANDS",
  //"STR_ENH_TOOLS_TEXTUREFINDER",
  //"STR_ENH_TOOLS_VARIABLEVIEWER",
  //Placement tools
  //"STR_ENH_FOLDER_PLACEMENTTOOLS",
  //"STR_ENH_TOOLS_ORIENTATEEAST",
  //"STR_ENH_TOOLS_ORIENTATENORTH",
  //"STR_ENH_TOOLS_ORIENTATESOUTH",
  //"STR_ENH_TOOLS_ORIENTATEWEST",
  //"STR_ENH_TOOLS_PLACEMENTTOOL",
  //"STR_ENH_TOOLS_RANDOMDIR",
  //"STR_ENH_TOOLS_REVERSEDIRECTION",
   //Loadout tools
  //"STR_ENH_FOLDER_LOADOUTTOOLS",
  //"STR_ENH_TOOLS_APPLYLOADOUTS",
  //"STR_ENH_TOOLS_COPYLOADOUTS",
  //"STR_ENH_TOOLS_EXPORTLOADOUT_CFGRESPAWNINVENTORY",
  //"STR_ENH_TOOLS_EXPORTLOADOUT_CONFIG",
  //"STR_ENH_TOOLS_INVENTORYMANAGER",
  //"STR_ENH_TOOLS_REMOVEGOGGLES",
  //"STR_ENH_TOOLS_REMOVEHEADGEAR",
  //"STR_ENH_TOOLS_REMOVENVGS",
  //"STR_ENH_TOOLS_REMOVEVESTS",
  //"STR_ENH_TOOLS_REMOVEWEAPONS",
  //Misc
  //"STR_ENH_FOLDER_MISCELLANEOUS",
  //"STR_ENH_TOOLS_DELETEEMPTYLAYERS",
  //"STR_ENH_TOOLS_DRAWBUILDINGPOSITIONS",
  //"STR_ENH_TOOLS_DRAWDLCICONS",
  //"STR_ENH_TOOLS_EXPORTMISSIONPARAMETERS",
  //"STR_ENH_TOOLS_GENERATESTEAMMISSIONDESCRIPTION",
  //"STR_ENH_TOOLS_SWITCHTIME",
  //"STR_ENH_TOOLS_TOGGLEAIFEATURES",
  //"STR_ENH_TOOLS_TOGGLEDYNAMICSIMULATION",
  //"STR_ENH_TOOLS_TOGGLEGRASS",
  //"STR_ENH_TOOLS_TOGGLESIMPLEOBJECT",
  //"STR_ENH_TOOLS_TOGGLESIMULATION",
  //Debug
  //"STR_ENH_FOLDER_DEBUGTOOLS",
  //"STR_ENH_TOOLS_CLEARCHAT",
  //"STR_ENH_TOOLS_PRODUCTINFO",
  //"STR_ENH_TOOLS_RECOMPILEFUNCTIONS",
  //"STR_ENH_TOOLS_SHOWMAPIDS",
  //GUI
  //"STR_ENH_FOLDER_GUI",
  //"STR_ENH_TOOLS_CONTROLSTYLES",
  //"STR_ENH_TOOLS_CONTROLTYPES",
  //"STR_ENH_TOOLS_EXPORTGUIBASECLASSES",
  //"STR_ENH_TOOLS_GUITESTGRIDS" //Last remaining entry MAY NOT be followed by a comma ","
];