action = "http://steamcommunity.com/sharedfiles/filedetails/?id=623475643";
actionName = "Workshop";
author = "R3vo";
hideName = 0;
hidePicture = 0;
logo = "x\enh\addons\main\data\logo_ca.paa";
logoOver = "x\enh\addons\main\data\logoOver_ca.paa";
logoSmall = "x\enh\addons\main\data\logoSmall_ca.paa";
name = "3den Enhanced v0.0.0";
overview = "This modification adds new functionalities to the Eden Editor. The modification is not needed for the scenarios to be played as no dependencies are created.<br/><a href='https://www.bohemia.net/community/licenses/arma-public-license-share-alike'><t underline='true'>This content is under APL-SA license.</t><br/></a><br/><t size='1.5'><img image='x\enh\addons\main\data\APL-SA_Custom_ca.paa' /></t>";
picture = "x\enh\addons\main\data\picture_ca.paa";
tooltipOwned = "This modification adds new functionalities to the Eden Editor. The modification is not needed for the scenarios to be played as no dependencies are created.";
