name = "3den Enhanced - Optionals";
author = "R3vo";
picture = "\3denEnhanced_Optionals\data\logo.paa";
logo = "\3denEnhanced_Optionals\data\logo.paa";
logoOver = "\3denEnhanced_Optionals\data\logo.paa";
logoSmall = "\3denEnhanced_Optionals\data\logo.paa";
actionName = "Workshop";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=2152689230";
tooltipOwned = "Allows the user to hide tools and attributes introduced by 3den Enhanced.";
overview = "Allows the user to hide tools and attributes introduced by 3den Enhanced.";
hideName = 0;
hidePicture = 0;