class CfgFontFamilies
{
    class ENH_BlankFont
    {
        fonts[] =
        {
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro9",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light6"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro10",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light7"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro11",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light8"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro12",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light9"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro13",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light10"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro14",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light11"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro15",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light12"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro16",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light13"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro17",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light14"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro18",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light15"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro19",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light16"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro20",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light17"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro21",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light18"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro22",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light19"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro23",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light20"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro24",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light21"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro25",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light22"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro26",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light23"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro27",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light24"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro28",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light25"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro29",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light26"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro30",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light27"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro31",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light28"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro34",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light29"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro35",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light30"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro37",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light31"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro46",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light34"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro46",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light35"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro46",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light37"
            },
            {
                "\x\enh\addons\main\data\fonts\EtelkaMonospacePro\EtelkaMonospacePro46",
                "\x\enh\addons\main\data\fonts\NotoSansCJK-Light\NotoSansCJK-Light46"}
        };
        credit = "Leopard20 ;)";
    };
};
