class ENH_EventHandlers
{
    collapsed = 1;
    displayName = "$STR_ENH_MAIN_ATTRIBUTES_EVENT_HANDLERS_DISPLAYNAME";
    class Attributes
    {
        class ENH_EventHandlers_Subcategory
        {
            description = "$STR_ENH_MAIN_OBJECT_ATTRIBUTES_EVENT_HANDLERS_DESCRIPTION";
            property = "ENH_EventHandlers_Subcategory";
            control = "ENH_SubCategoryNoHeader3_Fixed";
        };
        EH_CONFIG(AnimChanged,objectControllable);
        EH_CONFIG(AnimDone,objectControllable);
        EH_CONFIG(AnimStateChanged,objectControllable);
        EH_CONFIG(Assembled,objectControllable);
        EH_CONFIG(Attached,objectControllable + objectVehicle);
        EH_CONFIG(CargoLoaded,objectVehicle);
        EH_CONFIG(CargoUnloaded,objectVehicle);
        EH_CONFIG(ContainerClosed,objectHasInventoryCargo);
        EH_CONFIG(ContainerOpened,objectHasInventoryCargo);
        EH_CONFIG(ControlsShifted,objectVehicle);
        EH_CONFIG(Dammaged,1);
        EH_CONFIG(Deleted,1);
        EH_CONFIG(Detached,objectControllable + objectVehicle);
        EH_CONFIG(Disassembled,objectControllable);
        EH_CONFIG(Engine,objectVehicle);
        EH_CONFIG(EpeContact,1);
        EH_CONFIG(EpeContactEnd,1);
        EH_CONFIG(EpeContactStart,1);
        EH_CONFIG(Explosion,1);
        EH_CONFIG(Fired,objectControllable + objectVehicle);
        EH_CONFIG(FiredMan,objectControllable);
        EH_CONFIG(FiredNear,objectControllable + objectVehicle);
        EH_CONFIG(Fuel,objectVehicle);
        EH_CONFIG(Gear,objectVehicle);
        EH_CONFIG(GestureChanged,objectControllable);
        EH_CONFIG(GestureDone,objectControllable);
        EH_CONFIG(GetIn,objectVehicle);
        EH_CONFIG(GetInMan,objectControllable);
        EH_CONFIG(GetOut,objectVehicle);
        EH_CONFIG(GetOutMan,objectControllable);
        EH_CONFIG(HandleDamage,1);
        EH_CONFIG(HandleHeal,objectControllable);
        EH_CONFIG(HandleIdentity,objectControllable);
        EH_CONFIG(HandleRating,objectControllable);
        EH_CONFIG(HandleScore,objectControllable);
        EH_CONFIG(Hit,1);
        EH_CONFIG(HitPart,1);
        EH_CONFIG(IncomingMissile,objectVehicle);
        EH_CONFIG(InventoryClosed,objectControllable);
        EH_CONFIG(InventoryOpened,objectControllable);
        EH_CONFIG(Killed,objectControllable + objectVehicle);
        EH_CONFIG(LandedStopped,objectVehicle);
        EH_CONFIG(LandedTouchDown,objectVehicle);
        EH_CONFIG(Landing,objectVehicle);
        EH_CONFIG(LandingCanceled,objectControllable);
        EH_CONFIG(LeaningChanged,objectControllable);
        EH_CONFIG(Local,1);
        EH_CONFIG(MagazineUnloaded,objectControllable);
        EH_CONFIG(OpticsModeChanged,objectControllable + objectVehicle);
        EH_CONFIG(OpticsSwitch,objectControllable + objectVehicle);
        EH_CONFIG(PeriscopeElevationChanged,objectVehicle);
        EH_CONFIG(Put,objectControllable);
        EH_CONFIG(Reloaded,objectControllable + objectVehicle);
        EH_CONFIG(Respawn,objectControllable + objectVehicle);
        EH_CONFIG(RopeAttach,objectVehicle);
        EH_CONFIG(RopeBreak,objectVehicle);
        EH_CONFIG(SeatSwitched,objectVehicle);
        EH_CONFIG(SeatSwitchedMan,objectControllable);
        EH_CONFIG(SlotItemChanged,objectControllable);
        EH_CONFIG(SoundPlayed,objectControllable);
        EH_CONFIG(Suppressed,objectControllable);
        EH_CONFIG(Take,objectControllable);
        EH_CONFIG(TaskSetAsCurrent,objectControllable);
        EH_CONFIG(TurnIn,objectVehicle);
        EH_CONFIG(TurnOut,objectVehicle);
        EH_CONFIG(VisionModeChanged,objectControllable + objectVehicle);
        EH_CONFIG(WeaponAssembled,objectControllable);
        EH_CONFIG(WeaponChanged,objectControllable);
        EH_CONFIG(WeaponDeployed,objectControllable);
        EH_CONFIG(WeaponDisassembled,objectControllable);
        EH_CONFIG(WeaponRested,objectControllable);
    };
};
