##########################################################################################
############################## LAUNCH DEFAULT ############################################
##########################################################################################
[default]

workshop = [
    # Pythia
    "1751569185",
    # 7erra's Editing Extensions
    "1387934106",
    # 3Den Stringtable Viewer
    "2073243184",
    # Debug Console
    "1231625987",
    # SplinePlacer
    "3687041036",
    # # CBA
    "450814997",
    # ACE3
    "463939057",
    # Advanced Developer Tools
    # "3499977893"
]

parameters = [
    "-limitFPS=60"
]

mission = "3denEnhanced.VR" # Mission to launch directly into the editor with
executable = "arma3_x64"

##########################################################################################
############################## LAUNCH SPEARHEAD 1944 #####################################
##########################################################################################
[spe]
extends = "default"

workshop = [
    # SPEX
    "3117898674"
]

dlc = [
    "Spearhead 1944",
]

##########################################################################################
############################## LAUNCH PROFILING ##########################################
##########################################################################################
[profiling]
extends = "default"
executable = "arma3profiling_x64.exe"

##########################################################################################
############################## LAUNCH DIAG ##########################################
##########################################################################################
[diag]
extends = "default"
executable = "arma3diag_x64.exe"

##########################################################################################
############################## LAUNCH PLAYER #############################################
##########################################################################################
[player]
extends = "default"
parameters = [
    "-noPause",
    "-noPauseAudio",
    "-connect=127.0.0.1",
    "-port=2302"
]

##########################################################################################
############################## LAUNCH SERVER #############################################
##########################################################################################
[server]
extends = "default"
parameters = [
    "-server",
    "-port=2302",
    "-config=C:\\Users\\rober\\OneDrive\\Repositories\\3den-Enhanced\\.hemtt\\server.cfg"
]