name = "3den Enhanced"
mainprefix = "x"
prefix = "enh"
author = "R3vo"

[files]
include = [
    "LICENSE.md",
    "CONTRIBUTORS.md",
    "python_code/**",
    "keys/**"
]

exclude = [
    "*.xcf"
]

[version]
major = 8
minor = 6
patch = 2
git_hash = 0

[hemtt.build]
optional_mod_folders = true

[hemtt.release]
archive = true

[properties]
author = "R3vo"
url = "https://steamcommunity.com/sharedfiles/filedetails/?id=623475643"

[lints.sqf.command_case]
severity = "Error"
options.ignore = [
    "AGLtoASL",
    "ASLtoAGL",
    "groupID"
]

[lints.sqf.banned_commands]
options.banned = [
    "execVM",
    "opfor",
    "blufor",
    "resistance",
    "and",
    "or",
    "not",
    "vehicle"
]

[lints.sqf.var_all_caps]
enabled = true

[lints.stringtables.usage]
options.ignore = [
    "STR_ENH_MAIN_DAMAGE_*",
]

##########################################################################################
############################## LAUNCH DEFAULT ############################################
##########################################################################################
[hemtt.launch.default]

workshop = [
    # Pythia
    "1751569185",
    # 7erra's Editing Extensions
    "1387934106",
    # 3Den Stringtable Viewer
    "2073243184",
    # Debug Console
    "1231625987",
    # Advanced Developer Tools
    "3499977893"
]

parameters = [
    "-limitFPS=60"
]

mission = "3denEnhanced.VR" # Mission to launch directly into the editor with
executable = "arma3_x64"

##########################################################################################
############################## LAUNCH ACE ################################################
##########################################################################################
[hemtt.launch.ace]
extends = "default"

workshop = [
    # CBA_A3
    "450814997",
    # ACE3
    "463939057"
]

# dlc = [
#     "Contact",
#     "Global Mobilization",
#     "S.O.G. Prairie Fire",
#     "CSLA Iron Curtain",
#     "Western Sahara",
#     "Spearhead 1944",
#     "Reaction Forces"
# ]

##########################################################################################
############################## LAUNCH SPEARHEAD 1944 #####################################
##########################################################################################
[hemtt.launch.spe]
extends = "default"

workshop = [
    # SPEX
    "3117898674"
]

dlc = [
    "spe",
]

##########################################################################################
############################## LAUNCH PROFILING ##########################################
##########################################################################################
[hemtt.launch.profiling]
extends = "default"
executable = "arma3profiling_x64.exe"

##########################################################################################
############################## LAUNCH DIAG ##########################################
##########################################################################################
[hemtt.launch.diag]
extends = "default"
executable = "arma3diag_x64.exe"

##########################################################################################
############################## LAUNCH PLAYER #############################################
##########################################################################################
[hemtt.launch.player]
extends = "default"
parameters = [
    "-noPause",
    "-noPauseAudio",
    "-connect=127.0.0.1",
    "-port=2302"
]

##########################################################################################
############################## LAUNCH SERVER #############################################
##########################################################################################
[hemtt.launch.server]
extends = "default"
parameters = [
    "-server",
    "-port=2302",
    "-loadMissionToMemory",
    "-config=C:\\Users\\rober\\OneDrive\\Games\\Arma 3\\Arma 3 Mods\\3den-Enhanced\\.hemtt\\server.cfg"
]
