name = "3den Enhanced"
mainprefix = "x"
prefix = "enh"
author = "R3vo"

[files]
include = [
    "LICENSE.md",
    "CONTRIBUTORS.md",
    "python_code/**",
    "keys/**"
]

exclude = [
    "*.xcf"
]

[version]
major = 8
minor = 7
patch = 2
git_hash = 0

[hemtt.build]
optional_mod_folders = true

[hemtt.release]
archive = true
