class Cfg3DEN
{
    class EventHandlers
    {
        class ENH_EventScripts
        {
            EVENT_SCRIPT(onBeforeMissionPreview);
            EVENT_SCRIPT(onConnectingEnd);
            EVENT_SCRIPT(onConnectingStart);
            EVENT_SCRIPT(onCopy);
            EVENT_SCRIPT(onCut);
            EVENT_SCRIPT(onDeleteUnits);
            EVENT_SCRIPT(onEditableEntityAdded);
            EVENT_SCRIPT(onEditableEntityRemoved);
            EVENT_SCRIPT(onEntityAttributeChanged);
            EVENT_SCRIPT(onEntityDragged);
            EVENT_SCRIPT(onEntityMenu);
            EVENT_SCRIPT(onEntityParentChanged);
            EVENT_SCRIPT(onGridChange);
            EVENT_SCRIPT(onHistoryChange);
            EVENT_SCRIPT(onMapClosed);
            EVENT_SCRIPT(onMapOpened);
            EVENT_SCRIPT(onMessage);
            EVENT_SCRIPT(onMissionAttributeChanged);
            EVENT_SCRIPT(onMissionAutosave);
            EVENT_SCRIPT(onMissionExportMP);
            EVENT_SCRIPT(onMissionExportSP);
            EVENT_SCRIPT(onMissionListChange);
            EVENT_SCRIPT(onMissionLoad);
            EVENT_SCRIPT(onMissionNew);
            EVENT_SCRIPT(onMissionPreview);
            EVENT_SCRIPT(onMissionPreviewEnd);
            EVENT_SCRIPT(onMissionSave);
            EVENT_SCRIPT(onMissionSaveAs);
            EVENT_SCRIPT(onModeChange);
            EVENT_SCRIPT(onMoveGridDecrease);
            EVENT_SCRIPT(onMoveGridIncrease);
            EVENT_SCRIPT(onMoveGridToggle);
            EVENT_SCRIPT(onPaste);
            EVENT_SCRIPT(onPasteUnitOrig);
            EVENT_SCRIPT(onRedo);
            EVENT_SCRIPT(onRotateGridDecrease);
            EVENT_SCRIPT(onRotateGridIncrease);
            EVENT_SCRIPT(onRotateGridToggle);
            EVENT_SCRIPT(onScaleGridToggle);
            EVENT_SCRIPT(onSearchCreate);
            EVENT_SCRIPT(onSearchEdit);
            EVENT_SCRIPT(onSelectionChange);
            EVENT_SCRIPT(onServerToggle);
            EVENT_SCRIPT(onSubmodeChange);
            EVENT_SCRIPT(onSurfaceSnapToggle);
            EVENT_SCRIPT(onTerrainNew);
            EVENT_SCRIPT(onToggleMapIDs);
            EVENT_SCRIPT(onToggleMapTextures);
            EVENT_SCRIPT(onTogglePlaceEmptyVehicle);
            EVENT_SCRIPT(onUndo);
            EVENT_SCRIPT(onVerticalToggle);
            EVENT_SCRIPT(onWidgetArea);
            EVENT_SCRIPT(onWidgetNone);
            EVENT_SCRIPT(onWidgetRotation);
            EVENT_SCRIPT(onWidgetScale);
            EVENT_SCRIPT(onWidgetToggle);
            EVENT_SCRIPT(onWidgetTranslation);
            EVENT_SCRIPT(onWorkspacePartSwitch);
        };
    };
};