class Cfg3DEN
{
  class EventHandlers
  {
    class ENH_EventScripts
    {
      EH_DEF(onBeforeMissionPreview);
      EH_DEF(onConnectingEnd);
      EH_DEF(onConnectingStart);
      EH_DEF(onCopy);
      EH_DEF(onCut);
      EH_DEF(onDeleteUnits);
      EH_DEF(onEditableEntityAdded);
      EH_DEF(onEditableEntityRemoved);
      EH_DEF(onEntityAttributeChanged);
      EH_DEF(onEntityDragged);
      EH_DEF(onEntityMenu);
      EH_DEF(onEntityParentChanged);
      EH_DEF(onGridChange);
      EH_DEF(onHistoryChange);
      EH_DEF(onMapClosed);
      EH_DEF(onMapOpened);
      EH_DEF(onMessage);
      EH_DEF(onMissionAttributeChanged);
      EH_DEF(onMissionAutosave);
      EH_DEF(onMissionExportMP);
      EH_DEF(onMissionExportSP);
      EH_DEF(onMissionListChange);
      EH_DEF(onMissionLoad);
      EH_DEF(onMissionNew);
      EH_DEF(onMissionPreview);
      EH_DEF(onMissionPreviewEnd);
      EH_DEF(onMissionSave);
      EH_DEF(onMissionSaveAs);
      EH_DEF(onModeChange);
      EH_DEF(onMoveGridDecrease);
      EH_DEF(onMoveGridIncrease);
      EH_DEF(onMoveGridToggle);
      EH_DEF(onPaste);
      EH_DEF(onPasteUnitOrig);
      EH_DEF(onRedo);
      EH_DEF(onRotateGridDecrease);
      EH_DEF(onRotateGridIncrease);
      EH_DEF(onRotateGridToggle);
      EH_DEF(onScaleGridToggle);
      EH_DEF(onSearchCreate);
      EH_DEF(onSearchEdit);
      EH_DEF(onSelectionChange);
      EH_DEF(onServerToggle);
      EH_DEF(onSubmodeChange);
      EH_DEF(onSurfaceSnapToggle);
      EH_DEF(onTerrainNew);
      EH_DEF(onToggleMapIDs);
      EH_DEF(onToggleMapTextures);
      EH_DEF(onTogglePlaceEmptyVehicle);
      EH_DEF(onUndo);
      EH_DEF(onVerticalToggle);
      EH_DEF(onWidgetArea);
      EH_DEF(onWidgetNone);
      EH_DEF(onWidgetRotation);
      EH_DEF(onWidgetScale);
      EH_DEF(onWidgetToggle);
      EH_DEF(onWidgetTranslation);
      EH_DEF(onWorkspacePartSwitch);
    };
  };
};